apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "car-information-provider"
  description: "Car Information Provider Service"
  tags:
    - backend
    - data-layer
    - flogo
  links:
    - title: TIBCO Cloud Home
      url: https://cloud.tibco.com/
    - title: Documentation
      url: https://eu.integration.cloud.tibco.com/docs/index.html
    - title: TIBCO Cloud Integration
      url: https://eu.integration.cloud.tibco.com/applications
    - title: VSCode Editor (File)
      url: vscode://file/Users/hpeters/VSCodeFolders/tibco-next-flogo-demo/flogo-app-car-information-provider.json
    - title: VSCode Editor (Folder)
      url: vscode://file/Users/hpeters/VSCodeFolders/tibco-next-flogo-demo/
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/tibco-next-demo
    backstage.io/techdocs-ref: dir:.
#    backstage.io/kubernetes-id: bwce-ah-test-1
#    jenkins.io/job-full-name: Build_BWCE_EAR_DB
spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: operational-department
  providesApis: [ "car-information-api" ]
  consumesApis:
    - car-details-api
  dependsOn:
    - resource:default/cars-promotional-materials
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "car-information-api"
  description: "An API that provides car details, and points to resources"
  tags:
    - store
    - rest
  links:
    - url: https://github.com/TIBCO-Hub-Backstage/tibco-next-demo
      title: GitHub Repo
      icon: github
    - url: https://github.com/TIBCO-Hub-Backstage/tibco-next-demo/blob/master/sample-api.json
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  system: car-order-system
  owner: operational-department
  apiConsumedBy: [ "component:car-order-ui"]
  definition:
    $text: ./sample-api.json
