apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "car-analyzer"
  description: "Car Analytical Report"
  tags:
    - spotfire
    - data-layer
    - frontend
  links:
    - title: TIBCO Spotfire Home
      url: https://www.tibco.com/products/tibco-spotfire
    - title: Demos
      url: https://www.tibco.com/products/tibco-spotfire/learn/demos
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/tibco-next-demo
    backstage.io/techdocs-ref: dir:.
#    backstage.io/kubernetes-id: bwce-ah-test-1
#    jenkins.io/job-full-name: Build_BWCE_EAR_DB
spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: finance-department
  dependsOn:
    - resource:default/cars-database
    - resource:default/cars-promotional-materials
