apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  links:
    - title: TIBCO Cloud Home
      url: https://cloud.tibco.com/
    - title: Documentation
      url: https://eu.integration.cloud.tibco.com/docs/index.html
    - title: TIBCO Cloud Integration
      url: https://eu.integration.cloud.tibco.com/applications
    - title: VSCode Editor (File)
      url: vscode://file/${{ values.localFolder }}/flogo.json
    - title: VSCode Editor (Folder)
      url: vscode://file/${{ values.localFolder }}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
  providesApis: [ "${{values.name}}-api" ]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ${{values.name}}-api-location
spec:
  targets:
    - ./catalog-api.yaml
